location: ExternalLibs
sources:
  - repo: https://github.com/SamMousa/lua-eventsourcing.git
    name: lua-eventsourcing
    rev: v1.6.10
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      -
  - repo: https://github.com/ClassicLootManager/EventDispatcher.git
    name: LibEventDispatcher
    rev: v1.1.2
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      -
  - repo: https://github.com/lantisnt/LibLogger.git
    name: LibLogger
    rev: v1.2.1
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      -