# MIT License
#
# Copyright (c) 2021 Lantis / Classic Loot Manager team
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

location: ExternalLibs
sources:
  - repo: https://github.com/SamMousa/lua-eventsourcing.git
    name: lua-eventsourcing
    rev: v1.5.0
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      -
  - repo: https://github.com/lantisnt/LibLogger.git
    name: LibLogger
    rev: v1.2.1
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      -
  - repo: https://github.com/lantisnt/lib-st.git
    name: lib-st-4.1.2
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      -
# sources_locked:
#   - repo: https://github.com/SamMousa/lua-eventsourcing.git
#     name: lua-eventsourcing
#     rev: 443da66903199f6564406eca66e7793a4be15bb1
#     type: git
#     sparse_paths:
#       -
#     link:
#     links:
#       -
#     scripts:
#       -
#   - repo: https://github.com/lantisnt/LibLogger.git
#     name: LibLogger
#     rev: c3af2263e25c8f340964fdfd4962701feba85a84
#     type: git
#     sparse_paths:
#       -
#     link:
#     links:
#       -
#     scripts:
#       -
#   - repo: https://github.com/lantisnt/lib-st.git
#     name: lib-st-4.1.2
#     rev: d20a50bc039a3fbc2ef060d5d66f9e0401211e2b
#     type: git
#     sparse_paths:
#       -
#     link:
#     links:
#       -
#     scripts:
#       -
# default_group: ''
# groups:
#   -
